ruma/ruma-client-api

Cargo.toml, src/lib.rs, src/r0/membership.rs
My first attempt to contribute to Ruma :smile:.
I'll need some endpoints for my own project and intend to add them to this library.
I started with a single endpoint but will likely add more. This is mainly to see if I got everything right/what I have to improve. So feedback is appreciated.
For example, I'm not sure about the name of the module, since there are two ways to join a room (by id and by room alias) it cannot be `join_room`.
=> Add join by room id endpoint

src/r0/presence.rs, src/r0/redact.rs, src/r0/send.rs, src/r0/sync.rs, src/r0/tag.rs, src/r0/typing.rs, src/r0/voip.rs
This PR adds the following endpoints, grouped in commits by file:
- Typing endpoint
- `PUT /_matrix/client/r0/rooms/{roomId}/typing/{userId}`
- Presence endpoints
- `PUT /_matrix/client/r0/presence/{userId}/status`
- `GET /_matrix/client/r0/presence/{userId}/status`
- `POST /_matrix/client/r0/presence/list/{userId}`
- `GET /_matrix/client/r0/presence/list/{userId}`
- Tagging endpoints
- `PUT /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}`
- `GET /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags`
- `DELETE /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}`
- Sync endpoint
- `GET /_matrix/client/r0/sync`
- Sending endpoints
- `PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}`
- `PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}`
- `PUT …
=> Add various endpoints

src/r0/account.rs, src/r0/contact.rs, src/r0/media.rs, src/r0/membership.rs, src/r0/presence.rs, src/r0/room.rs, src/r0/search.rs, src/r0/session.rs
I also fixed a few trivial things.
=> Point-out inconsistencies with spec

Cargo.toml, src/r0/account.rs, src/r0/alias.rs, src/r0/config.rs, src/r0/contact.rs, src/r0/context.rs, src/r0/directory.rs, src/r0/filter.rs, src/r0/media.rs, src/r0/membership.rs, src/r0/presence.rs, src/r0/profile.rs, src/r0/receipt.rs, src/r0/redact.rs, src/r0/room.rs, src/r0/search.rs, src/r0/send.rs, src/r0/server.rs, src/r0/session.rs, src/r0/sync.rs, src/r0/tag.rs, src/r0/typing.rs, src/r0/voip.rs, src/unversioned.rs
Also fixes a few errors encountered in the process.
I took the liberty to rename the endpoints related to state events into something more explicit about their function. This is not final and probably requires bikeshedding, as per #10 
fixes #14
=> Update to ruma-api v0.3.

src/lib.rs, src/r0/config.rs, src/r0/room.rs, src/r0/send.rs, src/r0/session.rs, src/r0/sync.rs
I saw today that you had converted the membership modules, which I had already done before on my fork. So to avoid any additional duplication of work, here is a PR for what me and @rschulman have converted so far. (I took out the commit for the membership module though, that would probably just result in merge conflicts)
=> Use ruma-api-macros for more endpoints

src/lib.rs
=> associated_consts stabilized

Cargo.toml, src/lib.rs
This is the **third** part needed for the update of the crate *hyper*.
=> Update of hyper

src/r0/sync/sync_events.rs
Should fix https://github.com/ruma/ruma-api-macros/issues/3
CC @florianjacob
=> r0::sync::sync_events: Fix (de)serialization of filter argument

src/r0.rs, src/r0/user_directory.rs, src/r0/user_directory/search_users.rs
https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-user-directory-search
=> Add user directory endpoints

Cargo.toml, src/r0/context/get_context.rs, src/r0/presence/get_subscribed_presences.rs, src/r0/search/search_events.rs, src/r0/send/send_message_event.rs, src/r0/sync/get_member_events.rs, src/r0/sync/get_message_events.rs, src/r0/sync/get_state_events.rs, src/r0/sync/sync_events.rs, src/r0/tag/get_tags.rs
See https://github.com/ruma/ruma-api/pull/29.
Before this can be merged, ruma-api 0.12 has to be released. Otherwise, it's fully finished though, and simply serves to better display the work that's already happened in this area.
=> "Server side support"

src/r0/session.rs, src/r0/session/get_login_types.rs
=> Add endpoint for getting supported login types

CHANGELOG.md, src/r0/account.rs, src/r0/account/get_username_availability.rs
I also added a bit in the changelog for the last PR where I forgot to update it.
Fixes #67
=> Endpoint for username availability

CHANGELOG.md, src/r0/room.rs, src/r0/room/upgrade_room.rs
=> Add room upgrade endpoint.

src/r0/media.rs, src/r0/media/get_content.rs, src/r0/media/get_content_as_filename.rs, src/r0/media/get_media_config.rs, src/r0/media/get_media_preview.rs
Issue #39 had some open conversation, so I don't know if that needs more thought.
=> Add/modify media endpoints.

CHANGELOG.md, src/r0/account/deactivate.rs
=> Add request and response parameters for account deactiviation

CHANGELOG.md, src/r0/session.rs, src/r0/session/sso_login.rs
=> Add SSO login endpoint

src/r0/membership.rs
=> Fix #99, Remove a comment

src/r0/membership/get_member_events.rs
Should take care of #120
This is my first PR to `ruma-client-api`, I hope everything is in order!
=>  Add missing query parameters to members list endpoint

src/r0/sync/sync_events.rs, src/serde.rs
=> Update sync endpoint

CHANGELOG.md, src/error.rs
=> Add M_USER_DEACTIVATED to ErrorKind

CHANGELOG.md, CONTRIBUTING.md, src/error.rs, src/r0/capabilities/get_capabilities.rs, src/r0/config/set_global_account_data.rs, src/r0/config/set_room_account_data.rs, src/r0/directory/get_public_rooms_filtered.rs, src/r0/filter.rs, src/r0/keys/claim_keys.rs, src/r0/keys/get_keys.rs, src/r0/media/get_media_preview.rs, src/r0/membership/invite_user.rs, src/r0/room/create_room.rs, src/r0/session/get_login_types.rs, src/r0/session/login.rs, src/r0/state/create_state_event_for_empty_key.rs, src/r0/state/create_state_event_for_key.rs, src/r0/state/get_state_events_for_empty_key.rs, src/r0/state/get_state_events_for_key.rs, src/r0/uiaa.rs
=> Normalize serde_json imports

CHANGELOG.md, src/r0/search/search_events.rs
=> Update search endpoint to r0.6.0

src/r0/media/get_content_thumbnail.rs
=> Fix get_content_thumbnail response
