ruma/ruma-client-api

src/r0/membership.rs

- Add the remaining room membership endpoints
- moves `ThirdPartySigned` into the membership module to use it for `join_by_room_id_or_alias` and `join_by_room_id`
- use the `RoomIdOrAlias` enum to allow the user to supply either a room id or an alias, maybe there is a better way?

Add room membership endpoints

---

src/lib.rs
src/r0/account.rs
src/r0/alias.rs
src/r0/config.rs
src/r0/contact.rs
src/r0/context.rs
src/r0/membership.rs
src/r0/room.rs
src/r0/session.rs

I opted for adding a `[Matrix spec link(...)]` in the documentation of each endpoint. It seems both simple and clear to me.
The URLs are pretty long, so the markdown text ends-up pretty large, is it ok, or should something (but what ?) be done about that?
Fixes #2

Add link to the matrix spec for each endpoint.

---

src/lib.rs
src/r0/account.rs
src/r0/alias.rs
src/r0/contact.rs
src/r0/context.rs
src/r0/directory.rs
src/r0/events.rs
src/r0/filter.rs
src/r0/membership.rs
src/r0/presence.rs
src/r0/profile.rs
src/r0/redact.rs
src/r0/room.rs
src/r0/session.rs
src/r0/sync.rs
src/r0/typing.rs

This PR adds, separated in commits, the endpoints:
- for directory querying
- `GET /_matrix/client/r0/publicRooms`
- for profile querying and updating
- `GET /_matrix/client/r0/profile/{userId}/displayname`
- `PUT /_matrix/client/r0/profile/{userId}/displayname`
- `GET /_matrix/client/r0/profile/{userId}/avatar_url`
- `PUT /_matrix/client/r0/profile/{userId}/avatar_url`
- `GET /_matrix/client/r0/profile/{userId}`
- for filtering
- `POST /_matrix/client/r0/user/{userId}/filter`
- `GET /_matrix/client/r0/user/{userId}/filter/{filterId}`
- for event retrieving in rooms
- `GET /_matrix/client/r0/rooms/{roomId}/state`
- `GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}`
- `GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}`
- `GET …

Add more endpoints (publicrooms, profile, filter, events)

---

src/r0/events.rs

According to the spec the room members endpoint does not have an event_type parameter in the path, it is also not used in the `request_path` method.

Remove unused event_type parameter

---

src/r0/alias.rs
src/r0/config.rs
src/r0/context.rs

I think there are no more of them in the docs!
Fixes #9

Convert path parameters in docs from colon-snake-case to brace-lower-camel-case

---

src/r0/sync.rs

According to the spec, the response field is `chunk`, not `chunks`

The member event response contains the field chunk, not chunks

---

src/r0/directory.rs

The server response cannot be deserialized because the aliases
attribute can be missing.  Wrapped the alias attribute with an
Option to fix the issue.

Make aliases optional for global rooms query.

---

src/r0/sync.rs

Before, it would silently ignore them for defaults,
so long-polling was not possible because no timeout
was passed

Pass sync endpoint parameters according to spec

---

src/r0/sync.rs

it was just an omission from the spec.
See https://github.com/matrix-org/matrix-doc/pull/1244 (not yet merged as of now, but already confirmed as omission).

/rooms/{room_id}/members requires authentication

---

src/r0/session.rs

Version 0.3.0 of the client-server spec adds a `device_id` field to the
login request and response.  It is optional in the request.
See https://matrix.org/docs/spec/client_server/r0.3.0.html#post-matrix-client-r0-login for details.
I don't think this will be backwards compatible with ruma-client, but I'm submitting another PR there.

r0.3.0/login: Add device_id to request & response

---

src/r0/sync.rs

According to the spec: https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-sync
Without this, ruma-client fails to parse a /sync response containing invited rooms.

InviteState in Sync response is stripped events

---

.rustfmt.toml
Cargo.toml
src/lib.rs
src/r0/account.rs
src/r0/alias.rs
src/r0/config.rs
src/r0/contact.rs
src/r0/context.rs
src/r0/directory.rs
src/r0/filter.rs
src/r0/media.rs
src/r0/membership.rs
src/r0/presence.rs
src/r0/profile.rs
src/r0/receipt.rs
src/r0/redact.rs
src/r0/room.rs
src/r0/search.rs
src/r0/send.rs
src/r0/server.rs
src/r0/session.rs
src/r0/sync.rs
src/r0/tag.rs
src/r0/typing.rs
src/r0/voip.rs
src/unversioned.rs

This PR includes an a re-run of `cargo fmt` without any changes and the move to nested imports that I already did for most other ruma crates but forgot for this one as separate commits.

Update to Rust 2018

---

src/r0/filter.rs

to be able to distinguish between no inclusion list (everything is included) and an empty inclusion list (nothing is included)

Make inclusion lists in event filters optional

---

Cargo.toml
src/r0.rs
src/r0/thirdparty.rs
src/r0/thirdparty/get_location_for_protocol.rs
src/r0/thirdparty/get_location_for_room_alias.rs
src/r0/thirdparty/get_protocol.rs
src/r0/thirdparty/get_protocols.rs
src/r0/thirdparty/get_user_for_protocol.rs
src/r0/thirdparty/get_user_for_user_id.rs

This adds the `/_matrix/client/r0/thirdparty/*` endpoints.
Blocking issues:
Questions:
1. Do we want the types in `thirdparty.rs` in another crate, as they might be reused for ruma-appservice-api?
2. Do we want the `regexp` field in `FieldType` to be a `Regex` type?

Add third party network endpoints

---

CHANGELOG.md
src/r0.rs
src/r0/appservice.rs
src/r0/appservice/set_room_visibility.rs
src/r0/room.rs
src/r0/room/create_room.rs

The application service specification defines a single extension for the
client-server API. This endpoint can only be used by application
services.

Add application service extension

---

CHANGELOG.md
src/r0.rs
src/r0/keys.rs
src/r0/keys/claim_keys.rs
src/r0/keys/create_keys.rs
src/r0/keys/get_key_changes.rs
src/r0/keys/get_keys.rs
src/r0/keys/upload_keys.rs

Fixes #64 
I originally called the `/upload` endpoint `create_keys`, but I changed it to `upload_keys` since it isn't really about creating any new keys but about publishing them to the server, as far as I can tell from the spec. Let me know if you disagree with the naming.

Add key management endpoints

---

CHANGELOG.md
src/r0/session/get_login_types.rs

The previous version was expecting one level of nesting too many, i.e.:
{"type": {"type": "m.login.password"}}
This is a breaking change, so bump the version number too. (Let me know if I shouldn't do that; I'm not sure what Ruma's versioning policy is.)
Also, I kept the name `LoginType` rather than `LoginFlow`, because once the user-interactive authentication API with multiple-stage flows are supported, a `LoginFlow` will conceptually be a `Vec<LoginType>`.
cc @jplatte

Fix r0::session::get_login_types::Response

---

src/r0/sync/sync_events.rs

This obviously depends on https://github.com/ruma/ruma-events/commit/12d725113baa40d9004c36235f82ee4050547bee. Not sure how we handle these cross-repo features, but here is a PR.

sync_events: Parse the to-device events.

---

src/r0/sync/sync_events.rs

The heroes map is strictly optional and as is deserialization might fail
for the whole response unless we allow it to be optional.

sync_events: Create an empty heroes vector the response doesn't contain it.

---

CHANGELOG.md
src/r0/account.rs
src/r0/account/register.rs

Fixes #90, and #132.
`AuthenticationData` is also used in `/register`, so I combined the changes in the same PR. I can split it up the commits into separate PRs if necessary.

Update register endpoint

---

Cargo.toml
src/r0/message/get_message_events.rs
src/r0/sync/sync_events.rs
src/serde.rs
src/serde/json_string.rs

Resolving: When trying to send a `r0::message::get_message_events::Request` using `RoomEventFilter::default()` for the filter field returns an error with inner type Query(Custom("unsupported value")).
If this is on the right track I'll turn the println's into asserts and add doc's.

sync_events/get_message_events: ser/de filters to string

---

CHANGELOG.md
src/r0/client_exchange/send_event_to_device.rs

This fixes https://github.com/ruma/ruma-client-api/issues/139.

client_exchange: Use room messages to send out to-device events.

---

src/r0/message/create_message_event.rs
src/r0/state/create_state_event_for_empty_key.rs
src/r0/state/create_state_event_for_key.rs

As per https://github.com/matrix-org/matrix-doc/pull/2525. The spec has been fixed.

message/state: The event id is required in the response when sending events.

---

src/r0/sync/sync_events.rs

Opening this as a PR so others can easily look into the errors and there's a public thing to test against when trying to fix this in ruma-serde (where I'm pretty sure this error originates).

Add another test for sync_events request deserialization
